### ISSUE TITLE
bug/Field-hr_json-doesnt-have-a-default-value

### ISSUE THREAD

**Issue by NathSantos** [gleideveloper/gpd-plannig-tool#121]
Atualmente na branch develop, quando tentamos criar um produto aparece o erro `Field 'hr_json' doesn't have a default value`

![Image](https://github.com/gleideveloper/gpd-plannig-tool/assets/63311872/560f6188-49e2-45aa-b60e-ba38b3277e37)

**Comment by andrex-sh** [comment]
![image](https://github.com/gleideveloper/gpd-plannig-tool/assets/57808599/d8590da2-460e-4aae-acab-a5636675011c)
Eu subi um patch para isso em #117
Pode verificar se ainda ocorre?
