### ISSUE TITLE
task/FE-MaxAllocationDinamico

### ISSUE THREAD

**Issue by NathSantos** [gleideveloper/gpd-plannig-tool#84]
Essa task consiste em:

1. fazer com que os valores na coluna **"Maximum Allocation"**, seja a carga horária TOTAL daquele respectivo mês. (é basicamente a soma de todas as cargas horárias de todos os roles que PODEM ser alocados naquele mês)

![Image](https://github.com/gleideveloper/gpd-plannig-tool/assets/63311872/6e4f7e77-c669-44d2-ac9b-8df832ea6c6a)

**Comment by SolanoOliveira** [comment]
Feito 💋
