### ISSUE TITLE
feature/CriarPersistenciaRoles

### ISSUE THREAD

**Issue by LuizCarlosS** [gleideveloper/gpd-plannig-tool#87]
- [x] Criar Modelo: 
- [x] Criar Associação com #86 
- [x] Criar Repository
- [x] Criar Sequelize
- [x] Testar a Funcionalidade Populando o Banco

**Comment by gleideveloper** [comment]
@LuizCarlosS tive que criar a modelo Role para associar com a modelo Colaborador.

**Comment by LuizCarlosS** [comment]
@gleideveloper Ja subiu a branch? Eu posso pelo menos testar e popular o banco
